FROM python:3

{% if http_proxy is defined %}
ENV HTTP_PROXY {{ http_proxy }}
{% endif %}
{% if https_proxy is defined %}
ENV HTTPS_PROXY {{ https_proxy }}
{% endif %}
{% if no_proxy is defined %}
ENV NO_PROXY {{ no_proxy }}
{% endif %}

ADD requirements.txt /app/

WORKDIR /app

RUN pip install -r requirements.txt

ADD Procfile /app/
ADD main.py /app/
ADD .env /app/
ADD internal.key /app/
ADD internal.crt /app/

EXPOSE 5000:5000

CMD ["honcho", "start"]